/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Application = {
  _id: string;
  _type: "application";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  referenceId?: string;
  name?: string;
  email?: string;
  currentRole?: string;
  institution?: string;
  researchInterests?: Array<string>;
  portfolioUrl?: string;
  cvUrl?: string;
  motivation?: string;
  availability?: string;
  submittedAt?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
  >;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  category?:
    | "benchmark-update"
    | "research-paper"
    | "industry-insight"
    | "lab-news"
    | "policy";
  tags?: Array<string>;
  seoTitle?: string;
  seoDescription?: string;
  featured?: boolean;
};

export type Research = {
  _id: string;
  _type: "research";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  problemStatement?: string;
  summary?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  status?: "active" | "published" | "completed" | "seeking-collaborators";
  venue?: string;
  publishedAt?: string;
  paperUrl?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  audience?: Array<string>;
  lead?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
  team?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "person";
  }>;
  featured?: boolean;
  seekingCollaborators?: boolean;
  metrics?: Array<{
    label?: string;
    value?: string;
    type?: "human" | "ai" | "gap";
    _key: string;
  }>;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  name?: string;
  role?: string;
  title?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortBio?: string;
  fullBio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  email?: string;
  credentials?: Array<string>;
  researchFocus?: Array<string>;
  socialLinks?: {
    twitter?: string;
    googleScholar?: string;
    linkedin?: string;
    personalWebsite?: string;
    researchgate?: string;
  };
  isPrincipalInvestigator?: boolean;
  isActive?: boolean;
  joinedAt?: string;
  position?: number;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Application
  | Post
  | Research
  | Person
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./lib/sanity/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "research"] | order(featured desc, publishedAt desc, title asc) {   _id,  _type,  slug,  title,  problemStatement,  summary,  body,  status,  venue,  publishedAt,  paperUrl,  heroImage,  tags,  audience,  featured,  seekingCollaborators,  metrics,  lead->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  },  team[]->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  } }
export type AllProjectsQueryResult = Array<{
  _id: string;
  _type: "research";
  slug: Slug | null;
  title: string | null;
  problemStatement: string | null;
  summary: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  status: "active" | "completed" | "published" | "seeking-collaborators" | null;
  venue: string | null;
  publishedAt: string | null;
  paperUrl: string | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tags: Array<string> | null;
  audience: Array<string> | null;
  featured: boolean | null;
  seekingCollaborators: boolean | null;
  metrics: Array<{
    label?: string;
    value?: string;
    type?: "ai" | "gap" | "human";
    _key: string;
  }> | null;
  lead: {
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  } | null;
  team: Array<{
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  }> | null;
}>;
// Variable: projectBySlugQuery
// Query: *[_type == "research" && slug.current == $slug][0] {   _id,  _type,  slug,  title,  problemStatement,  summary,  body,  status,  venue,  publishedAt,  paperUrl,  heroImage,  tags,  audience,  featured,  seekingCollaborators,  metrics,  lead->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  },  team[]->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  } }
export type ProjectBySlugQueryResult = {
  _id: string;
  _type: "research";
  slug: Slug | null;
  title: string | null;
  problemStatement: string | null;
  summary: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  status: "active" | "completed" | "published" | "seeking-collaborators" | null;
  venue: string | null;
  publishedAt: string | null;
  paperUrl: string | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tags: Array<string> | null;
  audience: Array<string> | null;
  featured: boolean | null;
  seekingCollaborators: boolean | null;
  metrics: Array<{
    label?: string;
    value?: string;
    type?: "ai" | "gap" | "human";
    _key: string;
  }> | null;
  lead: {
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  } | null;
  team: Array<{
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  }> | null;
} | null;
// Variable: allPeopleQuery
// Query: *[_type == "person"] | order(isActive desc, isPrincipalInvestigator desc, position asc, name asc) {   _id,  _type,  slug,  name,  role,  title,  photo,  shortBio,  fullBio,  email,  credentials,  researchFocus,  socialLinks,  isPrincipalInvestigator,  isActive,  joinedAt,  position,  alumniYear,  currentInstitution }
export type AllPeopleQueryResult = Array<{
  _id: string;
  _type: "person";
  slug: Slug | null;
  name: string | null;
  role: string | null;
  title: string | null;
  photo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  email: string | null;
  credentials: Array<string> | null;
  researchFocus: Array<string> | null;
  socialLinks: {
    twitter?: string;
    googleScholar?: string;
    linkedin?: string;
    personalWebsite?: string;
    researchgate?: string;
  } | null;
  isPrincipalInvestigator: boolean | null;
  isActive: boolean | null;
  joinedAt: string | null;
  position: number | null;
  alumniYear: null;
  currentInstitution: null;
}>;
// Variable: personBySlugQuery
// Query: *[_type == "person" && slug.current == $slug][0] {    _id,  _type,  slug,  name,  role,  title,  photo,  shortBio,  fullBio,  email,  credentials,  researchFocus,  socialLinks,  isPrincipalInvestigator,  isActive,  joinedAt,  position,  alumniYear,  currentInstitution,  "authoredPosts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {    _id,    "slug": slug.current,    title,    excerpt,    publishedAt,    category,    postType  }[0..4]}
export type PersonBySlugQueryResult = {
  _id: string;
  _type: "person";
  slug: Slug | null;
  name: string | null;
  role: string | null;
  title: string | null;
  photo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortBio: string | null;
  fullBio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  email: string | null;
  credentials: Array<string> | null;
  researchFocus: Array<string> | null;
  socialLinks: {
    twitter?: string;
    googleScholar?: string;
    linkedin?: string;
    personalWebsite?: string;
    researchgate?: string;
  } | null;
  isPrincipalInvestigator: boolean | null;
  isActive: boolean | null;
  joinedAt: string | null;
  position: number | null;
  alumniYear: null;
  currentInstitution: null;
  authoredPosts: Array<{
    _id: string;
    slug: string | null;
    title: string | null;
    excerpt: string | null;
    publishedAt: string | null;
    category:
      | "benchmark-update"
      | "industry-insight"
      | "lab-news"
      | "policy"
      | "research-paper"
      | null;
    postType: null;
  }>;
} | null;
// Variable: allPostsQuery
// Query: *[_type == "post"] | order(featured desc, publishedAt desc) {   _id,  _type,  slug,  title,  excerpt,  body,  coverImage,  publishedAt,  category,  tags,  seoTitle,  seoDescription,  featured,  author->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  }, postType }
export type AllPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  slug: Slug | null;
  title: string | null;
  excerpt: string | null;
  body: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  category:
    | "benchmark-update"
    | "industry-insight"
    | "lab-news"
    | "policy"
    | "research-paper"
    | null;
  tags: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  featured: boolean | null;
  author: {
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  } | null;
  postType: null;
}>;
// Variable: newsPostsQuery
// Query: *[_type == "post" && (postType == "news" || !defined(postType))] | order(featured desc, publishedAt desc) {   _id,  _type,  slug,  title,  excerpt,  body,  coverImage,  publishedAt,  category,  tags,  seoTitle,  seoDescription,  featured,  author->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  }, postType }
export type NewsPostsQueryResult = Array<{
  _id: string;
  _type: "post";
  slug: Slug | null;
  title: string | null;
  excerpt: string | null;
  body: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  category:
    | "benchmark-update"
    | "industry-insight"
    | "lab-news"
    | "policy"
    | "research-paper"
    | null;
  tags: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  featured: boolean | null;
  author: {
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  } | null;
  postType: null;
}>;
// Variable: blogPostsQuery
// Query: *[_type == "post" && postType == "blog"] | order(featured desc, publishedAt desc) {   _id,  _type,  slug,  title,  excerpt,  body,  coverImage,  publishedAt,  category,  tags,  seoTitle,  seoDescription,  featured,  author->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  }, postType }
export type BlogPostsQueryResult = Array<never>;
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {   _id,  _type,  slug,  title,  excerpt,  body,  coverImage,  publishedAt,  category,  tags,  seoTitle,  seoDescription,  featured,  author->{    _id,    _type,    slug,    name,    role,    title,    photo,    shortBio,    credentials,    researchFocus,    socialLinks,    isPrincipalInvestigator,    isActive,    joinedAt,    position  }, postType }
export type PostBySlugQueryResult = {
  _id: string;
  _type: "post";
  slug: Slug | null;
  title: string | null;
  excerpt: string | null;
  body: Array<
    | ({
        _key: string;
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  category:
    | "benchmark-update"
    | "industry-insight"
    | "lab-news"
    | "policy"
    | "research-paper"
    | null;
  tags: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  featured: boolean | null;
  author: {
    _id: string;
    _type: "person";
    slug: Slug | null;
    name: string | null;
    role: string | null;
    title: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    shortBio: string | null;
    credentials: Array<string> | null;
    researchFocus: Array<string> | null;
    socialLinks: {
      twitter?: string;
      googleScholar?: string;
      linkedin?: string;
      personalWebsite?: string;
      researchgate?: string;
    } | null;
    isPrincipalInvestigator: boolean | null;
    isActive: boolean | null;
    joinedAt: string | null;
    position: number | null;
  } | null;
  postType: null;
} | null;
// Variable: activeAnnouncementQuery
// Query: *[_type == "announcement" && isActive == true] | order(_createdAt desc)[0] { _id, message, ctaText, ctaUrl, type }
export type ActiveAnnouncementQueryResult = null;
// Variable: allEventsQuery
// Query: *[_type == "event"] | order(date asc) { _id, title, date, location, description, eventUrl, type }
export type AllEventsQueryResult = Array<never>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "research"] | order(featured desc, publishedAt desc, title asc) { \n  _id,\n  _type,\n  slug,\n  title,\n  problemStatement,\n  summary,\n  body,\n  status,\n  venue,\n  publishedAt,\n  paperUrl,\n  heroImage,\n  tags,\n  audience,\n  featured,\n  seekingCollaborators,\n  metrics,\n  lead->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  },\n  team[]->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  }\n }': AllProjectsQueryResult;
    '*[_type == "research" && slug.current == $slug][0] { \n  _id,\n  _type,\n  slug,\n  title,\n  problemStatement,\n  summary,\n  body,\n  status,\n  venue,\n  publishedAt,\n  paperUrl,\n  heroImage,\n  tags,\n  audience,\n  featured,\n  seekingCollaborators,\n  metrics,\n  lead->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  },\n  team[]->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  }\n }': ProjectBySlugQueryResult;
    '*[_type == "person"] | order(isActive desc, isPrincipalInvestigator desc, position asc, name asc) { \n  _id,\n  _type,\n  slug,\n  name,\n  role,\n  title,\n  photo,\n  shortBio,\n  fullBio,\n  email,\n  credentials,\n  researchFocus,\n  socialLinks,\n  isPrincipalInvestigator,\n  isActive,\n  joinedAt,\n  position,\n  alumniYear,\n  currentInstitution\n }': AllPeopleQueryResult;
    '*[_type == "person" && slug.current == $slug][0] {\n  \n  _id,\n  _type,\n  slug,\n  name,\n  role,\n  title,\n  photo,\n  shortBio,\n  fullBio,\n  email,\n  credentials,\n  researchFocus,\n  socialLinks,\n  isPrincipalInvestigator,\n  isActive,\n  joinedAt,\n  position,\n  alumniYear,\n  currentInstitution\n,\n  "authoredPosts": *[_type == "post" && references(^._id)] | order(publishedAt desc) {\n    _id,\n    "slug": slug.current,\n    title,\n    excerpt,\n    publishedAt,\n    category,\n    postType\n  }[0..4]\n}': PersonBySlugQueryResult;
    '*[_type == "post"] | order(featured desc, publishedAt desc) { \n  _id,\n  _type,\n  slug,\n  title,\n  excerpt,\n  body,\n  coverImage,\n  publishedAt,\n  category,\n  tags,\n  seoTitle,\n  seoDescription,\n  featured,\n  author->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  }\n, postType }': AllPostsQueryResult;
    '*[_type == "post" && (postType == "news" || !defined(postType))] | order(featured desc, publishedAt desc) { \n  _id,\n  _type,\n  slug,\n  title,\n  excerpt,\n  body,\n  coverImage,\n  publishedAt,\n  category,\n  tags,\n  seoTitle,\n  seoDescription,\n  featured,\n  author->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  }\n, postType }': NewsPostsQueryResult;
    '*[_type == "post" && postType == "blog"] | order(featured desc, publishedAt desc) { \n  _id,\n  _type,\n  slug,\n  title,\n  excerpt,\n  body,\n  coverImage,\n  publishedAt,\n  category,\n  tags,\n  seoTitle,\n  seoDescription,\n  featured,\n  author->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  }\n, postType }': BlogPostsQueryResult;
    '*[_type == "post" && slug.current == $slug][0] { \n  _id,\n  _type,\n  slug,\n  title,\n  excerpt,\n  body,\n  coverImage,\n  publishedAt,\n  category,\n  tags,\n  seoTitle,\n  seoDescription,\n  featured,\n  author->{\n    _id,\n    _type,\n    slug,\n    name,\n    role,\n    title,\n    photo,\n    shortBio,\n    credentials,\n    researchFocus,\n    socialLinks,\n    isPrincipalInvestigator,\n    isActive,\n    joinedAt,\n    position\n  }\n, postType }': PostBySlugQueryResult;
    '*[_type == "announcement" && isActive == true] | order(_createdAt desc)[0] { _id, message, ctaText, ctaUrl, type }': ActiveAnnouncementQueryResult;
    '*[_type == "event"] | order(date asc) { _id, title, date, location, description, eventUrl, type }': AllEventsQueryResult;
  }
}
