import type {
  LabMemberVisualSeed,
  TeamDirectoryGroup,
  TeamDirectoryMember,
} from "@/types/team";

export const labMemberGroups: TeamDirectoryGroup[] = [
  {
    id: "active-profiles",
    label: "Active Profiles",
    order: 1,
  },
  {
    id: "archived-profiles",
    label: "Archived Profiles",
    order: 2,
  },
];

export const labMemberVisuals: LabMemberVisualSeed[] = [
  {
    id: "suvrankar-datta",
    name: "Dr. Suvrankar Datta",
    role: "",
    initials: "SD",
    image: "/team/suvrankar-datta.jpeg",
    isLead: true,
  },
  {
    id: "divya-buchireddygari",
    name: "Dr. Divya Buchireddygari",
    role: "Research Lead",
    initials: "DB",
    image: "/team/divya-buchireddygari.jpeg",
    isLead: false,
  },
  {
    id: "hakikat-bir-singh-bhatti",
    name: "Dr. Hakikat Bir Singh Bhatti",
    role: "Research Lead",
    initials: "HB",
    image: "/team/hakikat-bhatti.jpeg",
    isLead: true,
  },
  {
    id: "lakshmi-vennela-chowdary-kaza",
    name: "Dr. Lakshmi Vennela Chowdary Kaza",
    role: "Research Lead",
    initials: "LK",
    image: "/team/lakshmi-vennela.jpeg",
    isLead: false,
  },
  {
    id: "swarna-radhakrishnan",
    name: "Ms. Swarna Radhakrishnan",
    role: "Assistant Project Manager",
    initials: "SR",
    image: "/team/swarna-radhakrishnan.jpeg",
    isLead: false,
  },
  {
    id: "haritha-r",
    name: "Ms. Haritha R",
    role: "Junior Research Fellow",
    initials: "HR",
    image: "/team/haritha.jpeg",
    isLead: false,
  },
  {
    id: "gadha-lekshmi-p",
    name: "Ms. Gadha Lakshmi",
    role: "Junior Research Fellow",
    initials: "GL",
    image: "/team/gadha-lekshmi.jpeg",
    isLead: false,
  },
  {
    id: "siddharth-reddy-anthireddy",
    name: "Mr. Siddharth Reddy Anthireddy",
    role: "Full Stack Engineer / Automator of the Technical Staff",
    initials: "SA",
    image: "/team/siddharth-reddy.jpeg",
    isLead: false,
  },
  {
    id: "shreyas-reddy-k",
    name: "Dr Shreyas Reddy",
    role: "Research Lead",
    initials: "SR",
    image: "/team/shreyas-reddy.jpeg",
    isLead: true,
  },
  {
    id: "sarath-sasi",
    name: "Sarath Sasi",
    role: "Researcher",
    initials: "SS",
    image: "/team/sarath-sasi.jpeg",
    isLead: true,
  },
  {
    id: "mrudula-bhalke",
    name: "Dr. Mrudula Bhalke",
    role: "Researcher",
    initials: "MB",
    image: "/team/mrudula-bhalke.jpeg",
    isLead: false,
  },
  {
    id: "nishtha-mahajan",
    name: "Dr. Nishtha Mahajan",
    role: "Researcher",
    initials: "NM",
    image: "/team/nishtha-mahajan.jpeg",
    isLead: false,
  },
  {
    id: "bhavya-ratan-maroo",
    name: "Dr. Bhavya Ratan Maroo",
    role: "Researcher",
    initials: "BM",
    image: "/team/bhavya-ratan.jpeg",
    isLead: false,
  },
  {
    id: "kautik-singh",
    name: "Kautik Singh",
    role: "Researcher",
    initials: "KS",
    image: "/team/kautik-singh.jpeg",
    isLead: false,
  },
  {
    id: "upasana-karnwal",
    name: "Upasana Karnwal",
    role: "Researcher",
    initials: "UK",
    image: "/team/upasana-karnwal.jpeg",
    isLead: false,
  },
];

function getTeamMemberName(id: string): string {
  return (
    labMemberVisuals.find((member) => member.id === id)?.name ?? "Team Member"
  );
}

export const labMembers: TeamDirectoryMember[] = [
  {
    id: "suvrankar-datta",
    name: getTeamMemberName("suvrankar-datta"),
    tenure: "2025-Present",
    affiliation: "JIPEMER, AIIMS Delhi, Ashoka University",
    groupId: "active-profiles",
    isActive: true,
    position: 1,
    projectSlugs: [
      "radle-benchmark",
      "autonomous-report-generation",
      "data-commons",
      "india-ai-validation",
      "human-ai-collaboration",
      "healthcare-ai-governance",
    ],
  },
  {
    id: "hakikat-bir-singh-bhatti",
    name: getTeamMemberName("hakikat-bir-singh-bhatti"),
    tenure: "2025-Present",
    affiliation: "CRASH Lab, MBBS, IIT-Delhi",
    groupId: "active-profiles",
    isActive: true,
    position: 2,
    projectSlugs: ["radle-benchmark", "india-ai-validation"],
  },
  {
    id: "nishtha-mahajan",
    name: getTeamMemberName("nishtha-mahajan"),
    tenure: "2025-Present",
    affiliation: "Data Systems Fellow @ CRASH Lab",
    groupId: "active-profiles",
    isActive: true,
    position: 3,
    projectSlugs: ["data-commons", "india-ai-validation"],
  },
  {
    id: "upasana-karnwal",
    name: getTeamMemberName("upasana-karnwal"),
    tenure: "",
    affiliation: "",
    groupId: "active-profiles",
    isActive: true,
    position: 4,
    projectSlugs: [],
  },
  {
    id: "divya-buchireddygari",
    name: getTeamMemberName("divya-buchireddygari"),
    tenure: "2024-2025",
    affiliation: "",
    groupId: "active-profiles",
    isActive: true,
    position: 5,
    projectSlugs: ["india-ai-validation"],
  },
  {
    id: "shreyas-reddy-k",
    name: getTeamMemberName("shreyas-reddy-k"),
    tenure: "2025-Present",
    affiliation: "CRASH LAB",
    groupId: "active-profiles",
    isActive: true,
    position: 6,
    projectSlugs: ["autonomous-report-generation", "human-ai-collaboration"],
  },
  {
    id: "sarath-sasi",
    name: getTeamMemberName("sarath-sasi"),
    tenure: "2025-Present",
    affiliation: "CRASH LAB",
    groupId: "active-profiles",
    isActive: true,
    position: 7,
    projectSlugs: [],
  },
  {
    id: "swarna-radhakrishnan",
    name: getTeamMemberName("swarna-radhakrishnan"),
    tenure: "2025-Present",
    affiliation: "KCDH-A, Ashoka University",
    groupId: "active-profiles",
    isActive: true,
    position: 8,
    projectSlugs: [],
  },
  {
    id: "haritha-r",
    name: getTeamMemberName("haritha-r"),
    tenure: "2025-Present",
    affiliation: "KCDH-A, Ashoka University",
    groupId: "active-profiles",
    isActive: true,
    position: 9,
    projectSlugs: [],
  },
  {
    id: "gadha-lekshmi-p",
    name: getTeamMemberName("gadha-lekshmi-p"),
    tenure: "2025-Present",
    affiliation: "KCDH-A, Ashoka University",
    groupId: "active-profiles",
    isActive: true,
    position: 10,
    projectSlugs: [],
  },
  {
    id: "siddharth-reddy-anthireddy",
    name: getTeamMemberName("siddharth-reddy-anthireddy"),
    tenure: "2025-Present",
    affiliation: "KCDHA, IFRE",
    groupId: "active-profiles",
    isActive: true,
    position: 11,
    projectSlugs: ["human-ai-collaboration"],
  },
  {
    id: "lakshmi-vennela-chowdary-kaza",
    name: getTeamMemberName("lakshmi-vennela-chowdary-kaza"),
    tenure: "2025-Present",
    affiliation: "CRASH Lab, IIT-Bombay",
    groupId: "archived-profiles",
    isActive: false,
    position: 12,
    projectSlugs: ["radle-benchmark", "healthcare-ai-governance"],
  },
  {
    id: "mrudula-bhalke",
    name: getTeamMemberName("mrudula-bhalke"),
    tenure: "2025-Present",
    affiliation: "MS by Research @ Ashoka",
    groupId: "archived-profiles",
    isActive: false,
    position: 13,
    projectSlugs: ["autonomous-report-generation", "human-ai-collaboration"],
  },
  {
    id: "bhavya-ratan-maroo",
    name: getTeamMemberName("bhavya-ratan-maroo"),
    tenure: "2025-Present",
    affiliation: "Policy & Ethics Fellow @ Ashoka",
    groupId: "archived-profiles",
    isActive: false,
    position: 14,
    projectSlugs: ["data-commons", "healthcare-ai-governance"],
  },
  {
    id: "kautik-singh",
    name: getTeamMemberName("kautik-singh"),
    tenure: "2024-2025",
    affiliation: "Systems Engineer @ CRASH Lab",
    groupId: "archived-profiles",
    isActive: false,
    position: 15,
    projectSlugs: ["data-commons"],
  },
];
